services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py migrate &&
              python manage.py collectstatic --no-input &&
              mkdir -p /code/mediafiles/users/avatars &&
              cp -n /code/static/images/default_avatar.jpg /code/mediafiles/users/avatars/ &&
              chmod -R 777 /code/mediafiles &&
              daphne -b 0.0.0.0 -p 8000 django_project.asgi:application"
    networks:
      - default
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"   # HTTP port
      - "8443:443"  # HTTPS port - ajout de cette ligne
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs  # Monter le répertoire des certificats
    depends_on:
      - web
    networks:
      - default

  db:
    image: postgres:14
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432" # Exposer le port PostgreSQL

  redis:
      image: redis:alpine
      ports:
        - "6380:6380"
      command: redis-server --port 6380
      networks:
        - default
      volumes:
        - redis_data:/data
      healthcheck:
        test: ["CMD", "redis-cli", "-p", "6380", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data:

networks:
  default:
    name: django-network
