# Generated by Django 5.1.4 on 2025-03-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatistics',
            name='duration',
            field=models.FloatField(default=300.0),
        ),
    ]
