# Generated by Django 5.1.4 on 2025-04-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_gamestatistics_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='users/avatars/default_avatar.jpg', null=True, upload_to='', verbose_name='Avatar'),
        ),
    ]
