# Generated by Django 5.1.4 on 2025-04-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='users/avatars/', null=True, upload_to='', verbose_name='Avatar'),
        ),
    ]
