# Generated by Django 5.1.4 on 2025-04-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_delete_gamehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatistics',
            name='is_multiplayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamestatistics',
            name='opponent',
            field=models.CharField(default='AI', max_length=255),
        ),
        migrations.AlterField(
            model_name='gamestatistics',
            name='difficulty',
            field=models.CharField(choices=[('es', 'Easy'), ('md', 'Medium'), ('hd', 'Hard')], default='md', max_length=10),
        ),
    ]
