# Generated by Django 5.1.4 on 2025-04-08 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_gamestatistics_is_multiplayer_and_more'),
        ('chat', '0010_remove_tournament_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatistics',
            name='is_tournament',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamestatistics',
            name='tournament_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_stats', to='chat.tournamentmatch'),
        ),
    ]
