# Generated by Django 5.1.4 on 2025-04-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_gamestatistics_is_tournament_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestatistics',
            old_name='is_tournament',
            new_name='is_tournament_match',
        ),
        migrations.RemoveField(
            model_name='gamestatistics',
            name='tournament_match',
        ),
        migrations.AddField(
            model_name='gamestatistics',
            name='tournament_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gamestatistics',
            name='tournament_round',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamestatistics',
            name='difficulty',
            field=models.CharField(choices=[('es', 'Easy'), ('md', 'Medium'), ('hd', 'Hard')], default='md', max_length=2),
        ),
        migrations.AlterField(
            model_name='gamestatistics',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestatistics',
            name='opponent',
            field=models.CharField(default='AI', max_length=100),
        ),
    ]
