# Generated by Django 5.1.4 on 2025-04-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_tournamentparticipant_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='alias',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
